"""
Writer Node - Generates chapter drafts from facts and insights

This node synthesizes the key facts and insights extracted by the Analyst node
to generate a comprehensive chapter draft with board-level professional tone.
"""

import logging
from typing import Dict, Any, List

from rag_project.utils.logger import setup_logger

logger = setup_logger(__name__)


def writer_node(state: Dict[str, Any], llm_manager) -> Dict[str, Any]:
    """
    Generate chapter draft from key facts and insights.

    This node:
    1. Takes key_facts, insights, and context_summary from chapter_scratchpad
    2. Generates an 800-1200 character chapter with board-level tone
    3. Structures content: opening (2-3 sentences), body (2-3 subsections), closing (1-2 sentences)
    4. Includes citation markers [来源: xxx]
    5. Returns {"current_draft": draft_text}
    6. Handles errors with fallback message

    CRITICAL: This node MUST NOT access retrieved_docs directly from state.
    It should only use the processed key_facts and insights from the analyst.

    Args:
        state: Current workflow state containing:
            - chapter_title: Title of the current chapter
            - chapter_question: The research question
            - chapter_context: Optional context for the chapter
            - chapter_scratchpad: Dict with intermediate results including:
                - key_facts: List of extracted key facts (from Analyst)
                - insights: List of generated insights (from Analyst)
                - context_summary: Optional summary context
        llm_manager: LLMManager instance for content generation

    Returns:
        Dict with updates:
            - current_draft: Generated chapter draft text

    Example:
        >>> state = {
        ...     "chapter_title": "行业发展现状",
        ...     "chapter_question": "行业发展如何？",
        ...     "chapter_scratchpad": {
        ...         "key_facts": ["事实1", "事实2"],
        ...         "insights": ["洞察1"]
        ...     }
        ... }
        >>> result = writer_node(state, llm_manager)
        >>> draft = result["current_draft"]
        >>> len(draft) > 100
        True
    """
    chapter_title = state.get("chapter_title", "")
    chapter_question = state.get("chapter_question", "")
    chapter_context = state.get("chapter_context", "")
    chapter_scratchpad = state.get("chapter_scratchpad", {})

    # Get key facts and insights from scratchpad (processed by Analyst)
    key_facts = chapter_scratchpad.get("key_facts", [])
    insights = chapter_scratchpad.get("insights", [])
    context_summary = chapter_scratchpad.get("context_summary", "")
    document_summary = chapter_scratchpad.get("document_summary", "")

    logger.info(f"Writer node generating chapter '{chapter_title}' "
                f"with {len(key_facts)} facts and {len(insights)} insights")

    # Step 1: Generate chapter draft using LLM
    try:
        draft = _generate_chapter_draft(
            chapter_title=chapter_title,
            chapter_question=chapter_question,
            chapter_context=chapter_context,
            key_facts=key_facts,
            insights=insights,
            context_summary=context_summary,
            document_summary=document_summary,
            llm_manager=llm_manager
        )

        logger.info(f"Generated chapter draft ({len(draft)} characters)")

    except Exception as e:
        logger.error(f"Error generating chapter draft: {e}. Using fallback.")
        draft = _get_fallback_draft(chapter_title, key_facts, insights)

    # Step 2: Return only the current_draft (do not modify scratchpad)
    return {
        "current_draft": draft
    }


def _generate_chapter_draft(
    chapter_title: str,
    chapter_question: str,
    chapter_context: str,
    key_facts: List[str],
    insights: List[str],
    context_summary: str,
    document_summary: str,
    llm_manager
) -> str:
    """
    Use LLM to generate chapter draft from facts and insights.

    Args:
        chapter_title: Title of the chapter
        chapter_question: The research question
        chapter_context: Optional context
        key_facts: List of key facts extracted by Analyst
        insights: List of insights generated by Analyst
        context_summary: Optional context summary
        document_summary: Summary of retrieved documents
        llm_manager: LLMManager instance

    Returns:
        Generated chapter draft text

    Raises:
        Exception: If LLM call fails
    """
    # Generate prompt for chapter writing
    prompt = _generate_writing_prompt(
        chapter_title=chapter_title,
        chapter_question=chapter_question,
        chapter_context=chapter_context,
        key_facts=key_facts,
        insights=insights,
        context_summary=context_summary,
        document_summary=document_summary
    )

    # Invoke LLM with higher temperature for creative writing
    response = llm_manager.invoke(prompt, temperature=0.7)

    return response


def _generate_writing_prompt(
    chapter_title: str,
    chapter_question: str,
    chapter_context: str,
    key_facts: List[str],
    insights: List[str],
    context_summary: str,
    document_summary: str
) -> str:
    """
    Generate prompt for LLM chapter writing.

    Args:
        chapter_title: Title of the chapter
        chapter_question: The research question
        chapter_context: Optional context
        key_facts: List of key facts
        insights: List of insights
        context_summary: Optional context summary
        document_summary: Summary of retrieved documents

    Returns:
        Formatted prompt string
    """
    # Build facts section
    facts_section = ""
    if key_facts:
        facts_section = "\n关键事实 (Key Facts):\n" + "\n".join(f"- {fact}" for fact in key_facts)
    else:
        facts_section = "\n关键事实: 无"

    # Build insights section
    insights_section = ""
    if insights:
        insights_section = "\n重要洞察 (Key Insights):\n" + "\n".join(f"- {insight}" for insight in insights)
    else:
        insights_section = "\n重要洞察: 无"

    # Build context section
    context_parts = []
    if chapter_context:
        context_parts.append(f"背景: {chapter_context}")
    if context_summary:
        context_parts.append(f"摘要: {context_summary}")
    if document_summary:
        context_parts.append(f"参考文档摘要: {document_summary[:500]}...")

    context_section = "\n".join(context_parts) if context_parts else "无额外背景信息"

    return f"""你是一位专业的报告撰写专家，需要为董事会或高级管理层撰写专业的研究报告章节。

章节标题: {chapter_title}

研究问题: {chapter_question}

{context_section}

{facts_section}

{insights_section}

写作要求:
1. 篇幅: 800-1200字(中文字符)或800-1200个英文字符
2. 语气: 董事会级别，专业、客观、权威
3. 结构:
   - 开头 (2-3句话): 概述本章主题和核心观点
   - 主体 (2-3个小节): 详细阐述，使用小标题组织内容
   - 结尾 (1-2句话): 总结要点或提出展望

4. 内容要求:
   - 基于提供的关键事实和重要洞察进行撰写
   - 逻辑清晰，层次分明
   - 使用专业的商业和学术语言
   - 避免口语化表达

5. 引用要求:
   - 在适当位置添加引用标记，格式: [来源: 文件名] 或 [来源: 文件名, 页码]
   - 例如: [来源: doc1.pdf] 或 [来源: industry_report.pdf, page 5]
   - 引用应该与提供的关键事实相关联

6. 格式要求:
   - 使用markdown格式
   - 主体部分使用 ## 标记小节标题
   - 段落之间空一行

现在请撰写该章节内容:"""


def _get_fallback_draft(chapter_title: str, key_facts: List[str], insights: List[str]) -> str:
    """
    Generate fallback chapter draft when LLM fails.

    Args:
        chapter_title: Title of the chapter
        key_facts: List of key facts
        insights: List of insights

    Returns:
        Fallback draft text
    """
    logger.warning("Using fallback draft generation")

    # Build simple draft from available facts and insights
    draft_parts = []

    # Opening
    draft_parts.append(f"# {chapter_title}\n")
    draft_parts.append(f"本章节主要分析{chapter_title}的相关情况。\n")

    # Body - facts
    if key_facts:
        draft_parts.append("## 关键事实\n")
        for i, fact in enumerate(key_facts, 1):
            draft_parts.append(f"{i}. {fact}")
        draft_parts.append("")

    # Body - insights
    if insights:
        draft_parts.append("## 主要发现\n")
        for i, insight in enumerate(insights, 1):
            draft_parts.append(f"{i}. {insight}")
        draft_parts.append("")

    # Closing
    draft_parts.append("## 总结\n")
    draft_parts.append("由于技术原因，本章节内容为自动生成的简化版本。")
    draft_parts.append("建议后续进行人工完善和补充。")

    fallback_draft = "\n".join(draft_parts)

    return fallback_draft
